language: node_js

node_js:
- '0.10'

before_install:
- openssl aes-256-cbc -K $encrypted_0bfa14c60f16_key -iv $encrypted_0bfa14c60f16_iv -in .travis/deploy_key.enc -out .travis/deploy_key -d


after_success:
- chmod 600 .travis/deploy_key
- ssh-add .travis/deploy_key
- git remote add deploy ssh://ubuntu@54.164.28.255/home/ubuntu/shell-site.git
- git push deploy