language: node_js

node_js:
- '0.10'

before_install:
- openssl aes-256-cbc -K $encrypted_0bfa14c60f16_key -iv $encrypted_0bfa14c60f16_iv -in .travis/deploy_key.enc -out .travis/deploy_key -d
- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- echo -e "54.164.28.255 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDqtNvKiGQhSb9v+GayS45Qk4n5o4XZyzPCl3xx3jRdewoKFgtScYS/Yd0PmeMXFR9eMWwqwWkAxG3lB4GwTHqtCaIozW3t/uMgVtANOfryUWyLQkSTvUM7eYGv7rvPjEwTSR3lkGuSANXMp5D72f2xVrpr1h6vltX7St8U6EQvm4BnQtujU+brrYrS1ojcvfgRujALOJBRxe2vxNcKlUotNoiBWs/LwgUPkw83GAy9XrERJVuoFBitPYDUhwZ3IbfgMFEQ7K+6S9zk07SudCuODfBmFQA5DKfHyU834nudppMx2B6kTgi4Z7BUstfcMgiQwUXqwRBeiJ/1BvmNIzC3" >> ~/.ssh/known_hosts

after_success:
- chmod 600 .travis/deploy_key
- ssh-add .travis/deploy_key
- git remote add deploy ssh://ubuntu@54.164.28.255/home/ubuntu/shell-site.git
- git push deploy