language: node_js

node_js:
- '0.10'

before_install:
- openssl aes-256-cbc -K $encrypted_5fcd1d436920_key -iv $encrypted_5fcd1d436920_iv -in deploy_key.enc -out deploy_key -d

after_success:
- chmod 600 deploy_key
- ssh-add deploy_key
- git remote add deploy ssh://shell@104.131.88.177/home/shell/shell-site.git
- git push deploy