language: node_js
node_js:
- '0.10'
after_success:
- chmod 600 .travis/deploy_key
- ssh-add .travis/deploy_key
- git remote add deploy ssh://ubuntu@54.164.28.255/home/ubuntu/shell-site.git
- git push deploy
before_install:
- openssl aes-256-cbc -K $encrypted_5fcd1d436920_key -iv $encrypted_5fcd1d436920_iv -in deploy_key.enc -out .travis/deploy_key -d
