language: node_js
node_js:
- '0.10'

before_install:
- openssl aes-256-cbc -K $encrypted_5fcd1d436920_key -iv $encrypted_5fcd1d436920_iv -in deploy_key.enc -out deploy_key -d
- echo -e "104.131.88.177 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC1SdIhZeBOHtM4vopxbpi0Gvy0tkkI8l9pZVeXsFiggX2mp6N7ROVLsxRAL/5IftxQIi+xkdzwm3TPDkHsWuG5JuEK8+p8V5cnMaFKVAcVwGouUV/QnNAvD10MgCncD3yT+sh23LdCEWrucS/KlBv7nGW9w14+GWyvI4js2hryjI/KdKonOaLlLB8yCDqOTggtIY4y53yhXbOsFJUCUddqc40vakEZxQwvLJV24KU0FNWs96yupVnO0ctEDbezMx96wKr5j9HopFo+JRcw8IpZrLN7knntYXpb7XGU140j3grWzCz2XuUWKjrAe305LidlbIzPKnqecwPMxR766q+9" >> ~/.ssh/known_hosts
- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

after_success:
- cp deploy_key ~/.ssh/id_rsa
- cp id_rsa.pub ~/.ssh/id_rsa.pub
- chmod 600 ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa.pub
- git remote add deploy ssh://shell@104.131.88.177/home/shell/shell-site.git
- git push deploy master